### ISSUE TITLE
Wrong return error for deleteDatasetData

### ISSUE THREAD

**Issue by mereacre** [nqminds/nqm-api-tdx#15]
The below code return the error in ```then(...)``` instead of ```catch(...)``` for a list non existant primary keys

```javascript
const primaryKey = [{key1: value11, key2: value21}, {key1: value12, key2: value22},...]

tdxApi.deleteDatasetDataAsync(resourceId, primaryKey)
  .then((data) => {
    // Here the error is in data.response
    // "no data found with key ["value11","value21]"
    // "no data found with key ["value12","value22]"
  })
  .catch((err) => {
    // Process err
  });
```

**Comment by TobyEalden** [comment]
Think this is fixed by https://github.com/nqminds/nqm-core-command/commit/70a019170b31a840bf1e8fa918988fef9605620b, but might need an additional argument to determine the action to take if one of the deletes fails, i.e. continue attempting to delete  the others or abort.
